### ISSUE TITLE
Close tooltip-content when mouse over it

### ISSUE THREAD

**Issue by robba86** [mohsinulhaq/react-popper-tooltip#104]
**Is your feature request related to a problem? Please describe.**

I like to make the tooltip-content disappear when the target for the tooltip is not hovered any more. If you hover the actual tooltip-content it should close.

**Describe the solution you'd like**

An prop `closeOnToolTipHover={true}` // defaults to `false`

Or maybe, i did not find it, there already an option for this? :P

**Comment by mohsinulhaq** [comment]
You could use the component in controlled mode and hide `onMouseLeave` of the trigger.
Check this example out:
https://codesandbox.io/s/busy-water-q4vwc?file=/src/App.tsx

**Comment by robba86** [comment]
Awesome, thank you. I would figure it ut eventually but thought it was easier to reach out. Ill check out the example

**Comment by robba86** [comment]
Humz.. you solution did not seem to work that good, it kind of works as expected but when i have hovered an button and hover its tooltip, and i want to hover the button again it will not show (i think the position is where the tooltip is placed in that area when you hover your mouse over the button). Try adding more items and make some hover tests and you will see what i mean.

I tried solving this my self ofc but after a time i gave up for the day

**Comment by mohsinulhaq** [comment]
Got it. So the issue happens when you enter from the side from where the tooltip is supposed to appear. The issue is with the lib's arrow CSS. Its bounds extend a couple of pixels beyond the visible bounds because of the way it's made. Due to that when it appears over the trigger, it triggers a mouseleave and immediately triggers a hide.
You have two options:
- If you have your own tooltip CSS in your app, you might not face this issue if your arrow CSS is proper.
- If not, you can add the style `{ pointerEvents: 'none'}` to the tooltip. So that it doesn't interfere with the `mouseenter` and `mouseleave` of the trigger.

I have changed the codesandbox with the second solution. Do check it out and let me know.

**Comment by robba86** [comment]
Alright it works! Sweet.. now, how do i give you a beer?

**Comment by mohsinulhaq** [comment]
Haha, glad to hear it worked! Just a star to the library is enough for me 😃

**Comment by robba86** [comment]
> Haha, glad to hear it worked! Just a star to the library is enough for me

Thank you, a star it is then =)
