### ISSUE TITLE
Div not scrolling when cursor over popper

### ISSUE THREAD

**Issue by denchen** [mohsinulhaq/react-popper-tooltip#16]
First off, fantastic library. I had initially tried to make my own tooltip with Popper, using `react-popper` as a base, then I came across yours, which was way more robust than my implementation (especially with the trigger on mouse click), so I decided to give yours a try.

I'm having this issue where I'm not sure if it's something to do with your library, or an underlying issue with PopperJS itself, or I need to make some other adjustment (perhaps a modifier?) to get the behavior I desire.

I took [your Codebox example](https://codesandbox.io/s/pykkz77z5j) and [modified it so the trigger is within a scrollable div](https://codesandbox.io/s/918787xw0w). The issue is, when the popper is open, the div will not scroll if the cursor is over the popper, even though the cursor is still within the boundary of the scrollable div. This is unlike your example where if the cursor is over the popper, it still scrolls.

Again, not sure if it's a bug, a limitation, or something I need to implement to get it so I can still scroll even if the cursor is over the popper.

**Comment by denisborovikov** [comment]
Thanks!

`react-popper-tooltip` inserts the tooltip content before the [closing](https://github.com/mohsinulhaq/react-popper-tooltip/blob/23245d7671d7346615a03fec455c56b878fa07f9/src/TooltipTrigger.js#L221) `body` tag. This powerful feature allows you to show tooltip even if the tooltip trigger positioned inside the div with `overflow: hidden` and tooltip content won't be cut off.

Here's a simplified scheme of your layout
```html
<body>
  <div id="roop">
    <div class="App>
      <div class="left"></div>
      <div class=right">
        <div>tooltip trigger</div>
      </div>
    </div>
  </div>
  <div>tooltip content</div>
</body>
```
You can see, the `tooltip content` is not the child of the `right` div. Therefore the `right` doesn't hanlde `tooltip content`'s scroll events. Scroll events propagationed to the `body` tag, not to the `right` div.

In case of our example, `body` handles scroll events and content scrolling inside the `body` as well. That's why it works.

If you want to insert the tooltip content within the same parent as the tooltip trigger, you probably don't need this lib.

**Comment by mohsinulhaq** [comment]
I think not propagating scroll inside portals is desirable because of use cases like this: https://codesandbox.io/s/6zwmz219n3

**Comment by mohsinulhaq** [comment]
@denchen I have thought of a solution to this. Will make a PR this week. It will require quite some changes.

**Comment by denchen** [comment]
Ah, I see why the scrolling behavior is what it is. And, I agree, I can definitely see a use case like your example. Looking forward to your solution that can handle either scenario. Thanks!

**Comment by mohsinulhaq** [comment]
https://o93q4l92ny.codesandbox.io
v2.6.0 exposes a prop called `usePortal`
Setting it to false will disable the usage of React.createPortal to work for your use case
Also, you would need to set the scrolling container's position to relative.
Hope this helps.

**Comment by mohsinulhaq** [comment]
@denchen can you confirm if this works for you or not? If yes, then we can close this issue.

**Comment by denchen** [comment]
Hey, yeah, after a slight hiccup, I was able to get it to work. At first I thought it wasn't working, but then I realized I had to add a `position: relative` to the scrolling box, which is to be expected since the popper has a `position: absolute` on it.

Overall, I think the `usePortal` flag suits my purposes!

**Comment by mohsinulhaq** [comment]
okay then! closing...
