### ISSUE TITLE
Source in "dist" directory in v2.11.0 using ES2015+ syntax, v2.10.1 does not

### ISSUE THREAD

**Issue by tvsbrent** [mohsinulhaq/react-popper-tooltip#91]
**Describe the bug**
In examining the source files in version `2.11.0` ES2015+ syntax is used. I didn't see this mentioned in the release notes, so I'm assuming this was unintended. This is causing an issue when trying to use this library in IE11, as it doesn't support that syntax. (This library is a dependency of a Storybook library, so the tests of our frontend components fail in IE11 due to this. For the time being, I'm pinning the version to 2.10.1)

For example in `dist/cjs/react-popper-tooltip.js` the source on lines 9 through 12 is:

```
const TooltipContext = React.createContext({}); // eslint-disable-next-line @typescript-eslint/no-explicit-any

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const callAll = (...fns) => (...args) => fns.forEach(fn => fn && fn(...args));
```

In version `2.10.1` those lines are:
```
var TooltipContext = React.createContext({}); // eslint-disable-next-line @typescript-eslint/no-explicit-any

// eslint-disable-next-line @typescript-eslint/no-explicit-any
var callAll = function callAll() {
```

**To Reproduce**
1. Do a build and examine the source, ES2015+ syntax is in use.

**Expected behavior**
No ES2015+ syntax should be found.

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by mohsinulhaq** [comment]
Here's what happened:
https://github.com/mohsinulhaq/react-popper-tooltip/blob/8116f887e8cd3b344c6ef97c3fa8d8c2bdf44064/.browserslistrc#L3
IE11 was explicitly not supported before today's commit. But the transforms required by it was happening anyway because of the other queries in the `.browserslistrc`.
But after recent `@babel/preset-env` upgrade done before the recent release, browser list got updated and the transforms were no longer required according to it. Hence the issue.
I have now removed that explicit blacklisting, thereby adding IE11 support, as the `> 0.25%` query does include IE11. The changes are now released in [v2.11.1](https://github.com/mohsinulhaq/react-popper-tooltip/releases/tag/v2.11.1)

Please try and let me know.

**Comment by tvsbrent** [comment]
Just gave that a try and the Storybook instance worked fine in IE11. Thanks for the quick fix!

**Comment by mohsinulhaq** [comment]
Great, closing this issue then.
